prepare:
  rawdata_file_path: C:/Users/DELL/Desktop/my_ml_project/notebook/fever.csv
  target_column: "Fever_Severity_code"

preprocess:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  
  numerical_cols:
    - "Temperature"
    - "Age"
    - "BMI"
    - "Humidity"
    - "AQI"
    - "Heart_Rate"
  categorical_cols:
    - "Gender"
    - "Headache"
    - "Body_Ache"
    - "Fatigue"
    - "Chronic_Conditions"
    - "Allergies"
    - "Smoking_History"
    - "Alcohol_Consumption"
    - "Physical_Activity"
    - "Diet_Type"
    - "Blood_Pressure"
    - "Previous_Medication"
    - "Recommended_Medication"

preprocessing:
  numerical:
    imputer: "median"
    scaler: "standard"
  categorical:
    imputer: "most_frequent"
    encoder: "onehot"
    handle_unknown: "ignore"

model:
  model_type: "random_forest"
  random_state: 42
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
  logistic_regression:
    C: 1.0
    penalty: "l2"
    solver: "lbfgs"
    max_iter: 1000
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 1.0
    colsample_bytree: 1.0
  svm:
    C: 1.0
    kernel: "rbf"
  knn:
    n_neighbors: 5
    weights: "uniform"
  decision_tree:
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1

training:
  random_state: 42          # <-- matches dvc.yaml
  experiment_name: fever_severity_experiment
  tracking_uri: http://localhost:5000

cv:
  n_splits: 5
  random_state: 42
  strategy: "stratified"

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  threshold: 0.5

inference:
  confidence_threshold: 0.7
  batch_size: 100
